version: '3.1'
services:
  app:
    #image: shapeblock/nodejs-bp:1.0
    image: paketo-nodejs-mariadb
    env_file: .env
    ports:
        - "8080:8080"

  redis:
    image: redis
    restart: always
    env_file: .env

  # mysql:
  #   image: mysql
  #   restart: always
  #   env_file: .env

  mariadb:
    image: mariadb:10.4
    restart: always
    env_file: .env

  # elasticsearch:
  #   image: elasticsearch:7.9.3
  #   restart: always
  #   env_file: .env
      
  # postgres:
  #   image: postgres
  #   restart: always
  #   env_file: .env
